name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-16"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzIxOGU3NTAtN2NkMC00NTdkLWFmNGEtOTRlMGNhYWViZDc0IiwidGVuYW50X2lkIjoiYmMzYTAwNTU4MjYyMzg1MDgzYzNhODFhMWIyNGIwZDdhZWM2N2JiMzVjNTY1NTI4OWZjYzE0MjZhODEzZTkyYyIsImludGVybmFsX3NlY3JldCI6Ijk5Y2U4NGM4LWVjOGItNDgxZC1iOTM0LTJiYTg2MmJmNjRkYiJ9.WxR-MYrApbeAi_H-0ZJNLUmo70VYDMJL2AwQFuVRwGI"
JWT_SECRET="thisimverysecretownjwttokenthatiknowyoucannotdecodeyoucantrybutyouwontsuccedthisismychallengetoyouhahahhaha@@@f&&39bejioiueod9873426fhdkj#dslkj"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1